dialect = "uk"
enter_accept = false
inline_height = 40
search_mode = "fuzzy"
show_help = false
style = "auto"
sync_address = "https://atuin.milojevic.dev"
update_check = false

[stats]
common_subcommands = [
  "cargo",
  "go",
  "git",
  "kubectl",
  "k",
  "gcloud",
]

[sync]
records = true
