[tools]
flux2 = "latest"
fzf = "latest"
gcloud = "latest"
k9s = "latest"
kubectl = "latest"
neovim = "latest"
node = "latest"
php = "system"
python = "3.12.0"
ruby = "latest"
rust = "latest"
task = "latest"
terraform = "1.6.6"
zoxide = "latest"
helm = "latest"
lazygit = "latest"
kubectx = "latest"
go = "1.22"
direnv = "latest"
gitleaks = "latest"
ripgrep = "latest"
age = "latest"
shfmt = "latest"
atuin = "latest"
stern = "1.28.0"
pre-commit = "latest"
clickhouse = "latest"
skaffold = "latest"
hugo = "extended_0.102.3"
"cargo:cargo-binstall" = "latest"
"cargo:eza" = "latest"
"cargo:gping" = "latest"
"cargo:lsd" = "latest"
sops = "3.7.3"

[settings]
experimental = true
legacy_version_file = false
