customCommands:
  - key: "<c-u>"
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"
    subprocess: true
  - key: "<c-a>"
    command: aicommits -t conventional -g 2
    context: "global"
    subprocess: true
